### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by phirschybar** [edi-design/asana-hipchat#9]
I am getting the following 

```
ben@Canary008:~/asana_hipchat$ php asana.php
PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in /home/ben/asana_hipchat/lib/AsanaHipchat.php:157
Stack trace:
#0 /home/ben/asana_hipchat/lib/AsanaHipchat.php(157): PDO->__construct('sqlite:/home/be...')
#1 /home/ben/asana_hipchat/asana.php(39): AsanaHipchat->run()
#2 {main}
  thrown in /home/ben/asana_hipchat/lib/AsanaHipchat.php on line 157
```

**Comment by phirschybar** [comment]
nevermind. had to install the sqlite extension 

```
apt-get install php5-sqlite
```

**Comment by edi-design** [comment]
thanks for your comment.
i added this dependency to the README file.
